const CONTRACT_STATUS = {
  PENDING_LESSOR_SIGN: 1,
  PENDING_LESSEE_SIGN: 2,
  SIGNED: 3,
  REJECTED: 4,
  CANCELLED: 5,
  EXPIRED: 6
}

const CONTRACT_STATUS_TEXT = { 1: '待甲方签署', 2: '待乙方签署', 3: '已签署', 4: '已拒绝', 5: '已取消', 6: '已到期' }

const CONTRACT_STATUS_COLOR = { 1: '#FF976A', 2: '#FF976A', 3: '#07c160', 4: '#FF4D4F', 5: '#999999', 6: '#999999' }

const USER_ROLE = { LESSOR: 'LESSOR', LESSEE: 'LESSEE', ADMIN: 'ADMIN' }

const PAYMENT_METHODS = { 1: '押一付一', 2: '押一付三', 3: '押一付六', 4: '年付' }

const REAL_NAME_STATUS = { NOT_AUTH: 0, AUTHENTICATED: 1, AUTHENTICATING: 2, FAILED: 3 }

const SIGN_STATUS = { PENDING: 0, SIGNED: 1, REJECTED: 2, EXPIRED: 3 }

const APP_CONFIG = {
  DEFAULT_COMPANY_NAME: '内蒙古恒之寓酒店管理有限公司',
  TOKEN_REFRESH_THRESHOLD: 30 * 60 * 1000,
  AUTO_SAVE_INTERVAL: 30000,
  CONTRACT_DRAFT_KEY: 'contract_draft',
  DEFAULT_ADVANCE_NOTICE_DAYS: 30
}

module.exports = { CONTRACT_STATUS, CONTRACT_STATUS_TEXT, CONTRACT_STATUS_COLOR, USER_ROLE, PAYMENT_METHODS, REAL_NAME_STATUS, SIGN_STATUS, APP_CONFIG }
